[0m13:36:11.051476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D013CD0C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D015B47B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D015B47D90>]}


============================== 13:36:11.056477 | 1bb11e41-636c-45c8-81b6-05d46f1f7276 ==============================
[0m13:36:11.056477 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:36:11.057477 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\larch\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init wizeobsidian_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:36:11.074481 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': WindowsPath('C:/Users/larch/.dbt')}
[0m13:36:11.074481 [info ] [MainThread]: Creating dbt configuration folder at 
[0m13:36:11.077481 [debug] [MainThread]: Starter project path: C:\Users\larch\SynologyDrive\WizeObsidian\myenv\lib\site-packages\dbt\include\starter_project
[0m13:36:11.141496 [info ] [MainThread]: 
Your new dbt project "wizeobsidian_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:36:11.143497 [info ] [MainThread]: Setting up your profile.
[0m13:37:33.298506 [info ] [MainThread]: Profile wizeobsidian_project written to C:\Users\larch\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:37:33.300580 [debug] [MainThread]: Command `dbt init` succeeded at 13:37:33.300580 after 82.32 seconds
[0m13:37:33.301095 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D013CD0C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D015BA6B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D015CAE050>]}
[0m13:37:33.302130 [debug] [MainThread]: Flushing usage events
[0m13:37:33.951183 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:57:26.466674 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D2FAE0C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D319B0C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D319B09A0>]}


============================== 13:57:26.470675 | 1a37bbe5-41bf-4f40-b6eb-cac8ac674567 ==============================
[0m13:57:26.470675 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:57:26.471676 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\larch\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:57:26.472676 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\larch\SynologyDrive\WizeObsidian\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:57:26.474676 [debug] [MainThread]: Command `dbt run` failed at 13:57:26.473675 after 0.10 seconds
[0m13:57:26.474676 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D2FAE0C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D319B09A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D319B0C70>]}
[0m13:57:26.475676 [debug] [MainThread]: Flushing usage events
[0m13:57:27.158160 [debug] [MainThread]: An error was encountered while trying to flush usage events
